/home/jgarrayo/nextflow_tutorial/TCGA_nextflow/work/10/a3240844c0cd5f49946d73bc27c01c/.command.stub: line 45: ps: command not found
Package         Version
--------------- -------
numpy           1.15.2 
pandas          0.22.0 
pip             18.0   
python-dateutil 2.7.3  
pytz            2018.5 
setuptools      40.0.0 
six             1.11.0 
wheel           0.31.1 
/home/jgarrayo/nextflow_tutorial/TCGA_nextflow/work/10/a3240844c0cd5f49946d73bc27c01c/.command.stub: line 45: ps: command not found
The directory '/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/home/jgarrayo/nextflow_tutorial/TCGA_nextflow/work/10/a3240844c0cd5f49946d73bc27c01c/.command.stub: line 45: ps: command not found
You are using pip version 18.0, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
python: can't open file 'validation.py': [Errno 2] No such file or directory
